### ISSUE TITLE
RLLIBWrapper not working

### ISSUE THREAD

**Issue by LRKer** [cage-challenge/CybORG#6]
RLLIBWrapper.py contains path and import issues. When resolved, wrapper still yields an assertion error:

```
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 418, in setup
    self.workers = WorkerSet(
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 125, in __init__
    self.add_workers(
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 269, in add_workers
    self.foreach_worker(lambda w: w.assert_healthy())
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=15343, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fbcc4ecb8b0>)
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/RLLIB_training.py", line 33, in env_creator
    env = RLlibWrapper(env=cyborg, agent_name="Blue", max_steps=100)
  File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/ChallengeWrapper.py", line 19, in __init__
    env = OpenAIGymWrapper(agent_name=agent_name, env=env)
  File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 19, in __init__
    if isinstance(self.get_action_space(self.agent_name), list):
  File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 101, in get_action_space
    return self.action_space_change(self.env.get_action_space(agent))
  File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 115, in action_space_change
    assert type(action_space) is dict, \
AssertionError: Wrapper required a dictionary action space. Please check that the wrappers below return the action space as a dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/RLLIB_training.py", line 47, in <module>
    agent = ppo.PPOTrainer(config=config, env="CybORG")
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in setup
    raise e.args[0].args[2]
AssertionError: Wrapper required a dictionary action space. Please check that the wrappers below return the action space as a dict
(RolloutWorker pid=15343) /usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/gym/utils/seeding.py:47: DeprecationWarning: WARN: Function `rng.randint(low, [high, size, dtype])` is marked as deprecated and will be removed in the future. Please use `rng.integers(low, [high, size, dtype])` instead.
(RolloutWorker pid=15343)   deprecation(
(RolloutWorker pid=15343) 2022-10-12 18:45:56,027	ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=15343, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fbcc4ecb8b0>)
(RolloutWorker pid=15343)   File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
(RolloutWorker pid=15343)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=15343)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/RLLIB_training.py", line 33, in env_creator
(RolloutWorker pid=15343)     env = RLlibWrapper(env=cyborg, agent_name="Blue", max_steps=100)
(RolloutWorker pid=15343)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/ChallengeWrapper.py", line 19, in __init__
(RolloutWorker pid=15343)     env = OpenAIGymWrapper(agent_name=agent_name, env=env)
(RolloutWorker pid=15343)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 19, in __init__
(RolloutWorker pid=15343)     if isinstance(self.get_action_space(self.agent_name), list):
(RolloutWorker pid=15343)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 101, in get_action_space
(RolloutWorker pid=15343)     return self.action_space_change(self.env.get_action_space(agent))
(RolloutWorker pid=15343)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 115, in action_space_change
(RolloutWorker pid=15343)     assert type(action_space) is dict, \
(RolloutWorker pid=15343) AssertionError: Wrapper required a dictionary action space. Please check that the wrappers below return the action space as a dict
(RolloutWorker pid=15342) /usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/gym/utils/seeding.py:47: DeprecationWarning: WARN: Function `rng.randint(low, [high, size, dtype])` is marked as deprecated and will be removed in the future. Please use `rng.integers(low, [high, size, dtype])` instead.
(RolloutWorker pid=15342)   deprecation(
(RolloutWorker pid=15342) 2022-10-12 18:45:56,027	ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=15342, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fbea06ef880>)
(RolloutWorker pid=15342)   File "/usr/local/anaconda3/envs/rl_lib/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
(RolloutWorker pid=15342)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=15342)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/RLLIB_training.py", line 33, in env_creator
(RolloutWorker pid=15342)     env = RLlibWrapper(env=cyborg, agent_name="Blue", max_steps=100)
(RolloutWorker pid=15342)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/ChallengeWrapper.py", line 19, in __init__
(RolloutWorker pid=15342)     env = OpenAIGymWrapper(agent_name=agent_name, env=env)
(RolloutWorker pid=15342)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 19, in __init__
(RolloutWorker pid=15342)     if isinstance(self.get_action_space(self.agent_name), list):
(RolloutWorker pid=15342)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 101, in get_action_space
(RolloutWorker pid=15342)     return self.action_space_change(self.env.get_action_space(agent))
(RolloutWorker pid=15342)   File "/Users/4lk/cage-challenge-3/CybORG/CybORG/Agents/Wrappers/OpenAIGymWrapper.py", line 115, in action_space_change
(RolloutWorker pid=15342)     assert type(action_space) is dict, \
(RolloutWorker pid=15342) AssertionError: Wrapper required a dictionary action space. Please check that the wrappers below return the action space as a dict
```

Output of diff command to show path and import changes: `diff Wrappers/RLLIBWrapper.py RLLIBWrapper_altered.py`

```
6,7c6,9
< from CybORG.agents import B_lineAgent, GreenAgent
< from CybORG.agents.wrappers import ChallengeWrapper
---
> from CybORG.Agents import B_lineAgent, GreenAgent
> from CybORG.Agents.Wrappers import ChallengeWrapper
> from CybORG.Simulator.Scenarios.FileReaderScenarioGenerator import FileReaderScenarioGenerator
>
27c29
<     path = path[:-7] + f'/Shared/Scenarios/Scenario1b.yaml'
---
>     path = path[:-7] + f'/Simulator/Scenarios/scenario_files/scenario1b.yaml'
29,30c31,33
<     cyborg = CybORG(scenario_file=path, environment='sim', agents=agents)
<     env = RLlibWrapper(env=cyborg, agent_name="Blue,", max_steps=100)
---
>     sg = FileReaderScenarioGenerator(path)
>     cyborg = CybORG(scenario_generator=sg)
>     env = RLlibWrapper(env=cyborg, agent_name="Blue", max_steps=100)

```

**Comment by maxstanden** [comment]
I've made some changes to the documentation and the RLLib Wrapper, however the RLLib wrapper is not required for using RLLib in CAGE Challenge 3. Instead you can use the PettingZoo Parallel Wrapper as such:

```
from CybORG import CybORG
from CybORG.Simulator.Scenarios.DroneSwarmScenarioGenerator import DroneSwarmScenarioGenerator
from CybORG.Agents.Wrappers.PettingZooParallelWrapper import PettingZooParallelWrapper
from ray.rllib.env import ParallelPettingZooEnv
from ray.tune import register_env

def env_creator_CC3(env_config: dict):
    sg = DroneSwarmScenarioGenerator()
    cyborg = CybORG(scenario_generator=sg, environment='sim')
    env = ParallelPettingZooEnv(PettingZooParallelWrapper(env=cyborg))
    return env

register_env(name="CC3", env_creator=env_creator_CC3)
```
